on:
  workflow_dispatch:
  push:

jobs:
  oidc:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_AD_TENANT }}
        client-id: ${{ secrets.AZURE_OIDC_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
