on:
  workflow_dispatch:
  push:

jobs:
  oidc:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_AD_TENANT }}
        client-id: ${{ secrets.AZURE_OIDC_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Login to Azure Container Registry
      shell: pwsh
      run: |
        Install-Module -Name Az.ContainerRegistry -Force
        Connect-AzContainerRegistry -Name trevorsullivan
